"""Opal2 Glyph Cache
===================

Simple cache for storing glyph data generated by :class:`GlyphGenerator`.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Optional


class GlyphCache:
    """Cache glyphs to a JSON file for reuse."""

    def __init__(self, file: str = "opal2_glyph_cache.json"):
        self.path = Path(file)
        if self.path.exists():
            with open(self.path, "r", encoding="utf-8") as f:
                self.cache: Dict[str, Any] = json.load(f)
        else:
            self.cache = {}

    def get(self, symbol: str) -> Optional[Dict[str, Any]]:
        """Return glyph data for ``symbol`` if present."""
        return self.cache.get(symbol)

    def store(self, symbol: str, data: Dict[str, Any]) -> None:
        """Store glyph ``data`` keyed by ``symbol``."""
        self.cache[symbol] = data

    def save(self) -> None:
        """Write the cache to disk."""
        with open(self.path, "w", encoding="utf-8") as f:
            json.dump(self.cache, f, indent=2)

