"""Opal2 Glyph Cache
===================

Simple cache for storing glyph data generated by :class:`GlyphGenerator`.
Enhanced with async support for the Opal2 API.
"""

import asyncio
import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)

class GlyphCache:
    """Cache glyphs to a JSON file for reuse."""

    def __init__(self, file: str = "opal2_glyph_cache.json"):
        self.path = Path(file)
        self.stats = {"hits": 0, "misses": 0, "total_items": 0, "last_accessed": None}

        if self.path.exists():
            try:
                with open(self.path, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    self.cache: Dict[str, Any] = data.get("cache", {})
                    self.stats = data.get("stats", self.stats)
            except (json.JSONDecodeError, KeyError):
                self.cache = {}
                logger.warning(f"Cache file {self.path} corrupted, starting fresh")
        else:
            self.cache = {}

    def get(self, symbol: str) -> Optional[Dict[str, Any]]:
        """Return glyph data for ``symbol`` if present."""
        result = self.cache.get(symbol)
        if result:
            self.stats["hits"] += 1
        else:
            self.stats["misses"] += 1
        self.stats["last_accessed"] = datetime.now().isoformat()
        return result

    async def get_async(self, symbol: str) -> Optional[Dict[str, Any]]:
        """Async version of get method"""
        return await asyncio.to_thread(self.get, symbol)

    def store(self, symbol: str, data: Dict[str, Any]) -> None:
        """Store glyph ``data`` keyed by ``symbol``."""
        self.cache[symbol] = data
        self.stats["total_items"] = len(self.cache)

    async def set_async(self, symbol: str, data: Dict[str, Any]) -> None:
        """Async version of store method"""
        await asyncio.to_thread(self.store, symbol, data)

    def save(self) -> None:
        """Write the cache to disk."""
        try:
            cache_data = {
                "cache": self.cache,
                "stats": self.stats,
                "saved_at": datetime.now().isoformat(),
            }
            with open(self.path, "w", encoding="utf-8") as f:
                json.dump(cache_data, f, indent=2)
        except Exception as e:
            logger.error(f"Failed to save cache: {e}")

    async def save_async(self) -> None:
        """Async version of save method"""
        await asyncio.to_thread(self.save)

    async def get_stats(self) -> Dict[str, Any]:
        """Get cache statistics"""
        return {
            **self.stats,
            "cache_size": len(self.cache),
            "hit_rate": self.stats["hits"]
            / max(self.stats["hits"] + self.stats["misses"], 1)
            * 100,
        }

    async def clear_async(self) -> int:
        """Clear the cache and return number of items cleared"""
        item_count = len(self.cache)
        self.cache.clear()
        self.stats["total_items"] = 0
        await self.save_async()
        return item_count

    def __len__(self) -> int:
        """Return cache size"""
        return len(self.cache)

    def __contains__(self, symbol: str) -> bool:
        """Check if symbol exists in cache"""
        return symbol in self.cache
