
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurora-gui-cloudhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aurora-gui
  template:
    metadata:
      labels:
        app: aurora-gui
    spec:
      containers:
      - name: aurora-gui
        image: aurora-gui-cloudhub:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: aurora-gui-service
spec:
  type: NodePort
  selector:
    app: aurora-gui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
