#!/usr/bin/env python3
"""Build Synergy Dashboard from registry and repo files."""

import json
import os
import sys
from pathlib import Path
from typing import Dict, List, Set


def load_registry(registry_path: str) -> Dict:
    """Load the registry.json file."""
    try:
        with open(registry_path, 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"Error: Registry file not found at {registry_path}")
        return {"agents": [], "components": []}
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in registry file: {e}")
        return {"agents": [], "components": []}


def scan_python_files(repo_root: str) -> Set[str]:
    """Scan repository for Python files and extract component names."""
    components = set()
    repo_path = Path(repo_root)
    
    for py_file in repo_path.rglob('*.py'):
        # Skip virtual environments and hidden directories
        if any(part.startswith('.') or part == 'venv' for part in py_file.parts):
            continue
        
        try:
            with open(py_file, 'r', encoding='utf-8') as f:
                content = f.read()
                # Simple heuristic: look for class definitions
                for line in content.split('\n'):
                    if line.strip().startswith('class '):
                        class_name = line.split('class ')[1].split('(')[0].split(':')[0].strip()
                        components.add(class_name)
        except Exception as e:
            print(f"Warning: Could not read {py_file}: {e}")
    
    return components


def build_dashboard_table(registry: Dict, discovered_components: Set[str]) -> str:
    """Build the Markdown table for the dashboard."""
    lines = []
    lines.append("# Synergy Dashboard")
    lines.append("")
    lines.append("Auto-generated dashboard showing agents, components, and their relationships.")
    lines.append("")
    lines.append("## Agents")
    lines.append("")
    lines.append("| Name | Version | Description | Dependencies | Status |")
    lines.append("|------|---------|-------------|--------------|--------|")
    
    for agent in registry.get('agents', []):
        name = agent.get('name', 'N/A')
        version = agent.get('version', 'N/A')
        description = agent.get('description', 'N/A')
        deps = ', '.join(agent.get('dependencies', []))
        status = agent.get('status', 'unknown')
        lines.append(f"| {name} | {version} | {description} | {deps} | {status} |")
    
    lines.append("")
    lines.append("## Components")
    lines.append("")
    lines.append("| Name | Version | Description | Dependencies | Status |")
    lines.append("|------|---------|-------------|--------------|--------|")
    
    for component in registry.get('components', []):
        name = component.get('name', 'N/A')
        version = component.get('version', 'N/A')
        description = component.get('description', 'N/A')
        deps = ', '.join(component.get('dependencies', []))
        status = component.get('status', 'unknown')
        lines.append(f"| {name} | {version} | {description} | {deps} | {status} |")
    
    lines.append("")
    lines.append("## Discovered Python Classes")
    lines.append("")
    if discovered_components:
        lines.append("The following Python classes were discovered in the repository:")
        lines.append("")
        for comp in sorted(discovered_components):
            lines.append(f"- {comp}")
    else:
        lines.append("No Python classes discovered.")
    
    lines.append("")
    lines.append("---")
    lines.append("*Last updated: Auto-generated by build_dashboard.py*")
    
    return '\n'.join(lines)


def main():
    """Main entry point."""
    # Determine paths
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent.parent
    registry_path = repo_root / '.github' / 'registry' / 'registry.json'
    dashboard_path = repo_root / '.github' / 'dashboards' / 'synergy_dashboard.md'
    
    print(f"Loading registry from: {registry_path}")
    registry = load_registry(str(registry_path))
    
    print(f"Scanning Python files in: {repo_root}")
    discovered = scan_python_files(str(repo_root))
    print(f"Discovered {len(discovered)} Python classes")
    
    print("Building dashboard...")
    dashboard_content = build_dashboard_table(registry, discovered)
    
    # Ensure dashboard directory exists
    dashboard_path.parent.mkdir(parents=True, exist_ok=True)
    
    print(f"Writing dashboard to: {dashboard_path}")
    with open(dashboard_path, 'w') as f:
        f.write(dashboard_content)
    
    print("Dashboard built successfully!")


if __name__ == '__main__':
    main()
