*

!Dockerfile_aurora_gui_cloudhub
!requirements-hashed.txt

!api/
!api/aurora_gui_cloudhub_fastapi.py

!modules/
!modules/**

!src/
!src/**

!static/
!static/**

**/__pycache__/
**/*.py[cod]
**/.DS_Store
