#!/bin/bash

# 🔧 AURORA CLOUDBANK - CONTAINER REBUILD COMMAND FINDER
# Helps locate and execute the container rebuild command

echo "🔧 AURORA CLOUDBANK - CONTAINER REBUILD COMMAND FINDER"
echo "====================================================="
echo ""

echo "🔍 FINDING THE REBUILD COMMAND:"
echo "==============================="
echo ""

echo "📋 Method 1: Command Palette (Most Common)"
echo "• Press: Ctrl+Shift+P (Windows/Linux) or Cmd+Shift+P (Mac)"
echo "• Type one of these commands:"
echo "  - 'Dev Containers: Rebuild Container'"
echo "  - 'Remote-Containers: Rebuild Container'"
echo "  - 'Codespaces: Rebuild Container'"
echo "  - Just type 'rebuild' and look for container options"
echo ""

echo "📋 Method 2: Bottom Status Bar"
echo "• Look at the bottom-left corner of VS Code"
echo "• Click on the green/blue connection indicator"
echo "• Should show 'Dev Container' or 'Codespaces'"
echo "• Click it to see container options including rebuild"
echo ""

echo "📋 Method 3: Remote Explorer"
echo "• Open the Remote Explorer (Ctrl+Shift+E)"
echo "• Look for 'Dev Containers' or 'Codespaces' section"
echo "• Right-click on your container"
echo "• Select 'Rebuild Container'"
echo ""

echo "📋 Method 4: Terminal Method (Alternative)"
echo "• Close VS Code completely"
echo "• Reopen VS Code"
echo "• Reopen the repository/workspace"
echo "• You should be prompted to rebuild the container"
echo ""

echo "📋 Method 5: GitHub Codespaces Menu"
echo "• If you're in GitHub Codespaces:"
echo "• Click the hamburger menu (≡) in the top-left"
echo "• Look for 'Codespaces' or 'Container' options"
echo "• Select 'Rebuild Container'"
echo ""

echo "📋 Method 6: Settings Menu"
echo "• Go to File > Preferences > Settings"
echo "• Search for 'dev container' or 'remote container'"
echo "• Look for rebuild options"
echo ""

echo "🔧 CURRENT ENVIRONMENT CHECK:"
echo "============================="
echo "• Current directory: $(pwd)"
echo "• VS Code Remote: $(echo $VSCODE_REMOTE_CONNECTION_DATA | head -c 50)..."
echo "• Container indicator should be visible in bottom-left of VS Code"
echo ""

echo "⚠️  TROUBLESHOOTING:"
echo "==================="
echo "If you can't find the rebuild command:"
echo ""
echo "1. Check if you're in a Dev Container:"
echo "   • Bottom-left corner should show 'Dev Container' or similar"
echo "   • If not, you might not be in a container environment"
echo ""
echo "2. Try restarting VS Code:"
echo "   • Close VS Code completely"
echo "   • Reopen it"
echo "   • The rebuild option should appear"
echo ""
echo "3. Check VS Code extensions:"
echo "   • Make sure 'Dev Containers' extension is installed"
echo "   • Extension ID: ms-vscode-remote.remote-containers"
echo ""
echo "4. Manual rebuild via terminal:"
echo "   • You can also restart the entire Codespace"
echo "   • Go to your GitHub Codespaces dashboard"
echo "   • Stop and restart this Codespace"
echo ""

echo "🎯 QUICK TEST:"
echo "=============="
echo "Try pressing Ctrl+Shift+P right now and type 'rebuild'"
echo "You should see options like:"
echo "• 'Dev Containers: Rebuild Container'"
echo "• 'Remote-Containers: Rebuild Container'"
echo "• 'Codespaces: Rebuild Container'"
echo ""

echo "💡 ALTERNATIVE: Force Container Restart"
echo "======================================"
echo "If rebuild command is not available:"
echo "1. Go to https://github.com/codespaces"
echo "2. Find your Aurora CloudBank codespace"
echo "3. Click the '...' menu next to it"
echo "4. Select 'Stop codespace'"
echo "5. Wait for it to stop"
echo "6. Click 'Start' to restart with new container configuration"
echo ""

echo "🚀 AFTER REBUILD:"
echo "================"
echo "Once rebuilt, run this to test:"
echo "  ./test_copilot_terminal.sh"
echo ""
echo "The new prompt should be simple: user@host:~/path$"
echo "And Copilot Chat should be able to see terminal output!"
echo ""

echo "📞 NEED HELP?"
echo "============="
echo "If you're still having trouble finding the rebuild command:"
echo "1. Check the bottom-left corner of VS Code for the remote indicator"
echo "2. Try the Command Palette: Ctrl+Shift+P"
echo "3. Look for any 'Dev Container' or 'Codespaces' menus"
echo "4. As a last resort, restart the entire Codespace from GitHub"
echo ""

echo "✅ Ready to rebuild your Aurora CloudBank container!"
