#!/usr/bin/env python3
"""
Artifact Manager for Command Chain Execution
=============================================
Anchor: CMD-CHAIN-ARTIFACT-MGR-001
Team: AUo959-team
Ethics: Picard_Delta_3
DLP: CONFIDENTIAL

Manages post-commit artifacts generated by git hooks to prevent
interference with git operations (particularly rebase during sync).

Pattern:
  Detect → Stash → Execute → Restore
"""

import logging
import subprocess
from datetime import datetime, UTC
from pathlib import Path
from typing import List, Optional

logger = logging.getLogger(__name__)


class ArtifactManager:
    """Manages artifacts generated by post-commit hooks"""

    # Known artifacts generated by post-commit hooks
    KNOWN_ARTIFACTS = [
        '.aurora/audit_trail.json',
        '.security/scan_log.json',
        '.rebuild_prevention_status.json'
    ]

    def __init__(self, workspace_path: Optional[Path] = None):
        """
        Initialize artifact manager.

        Args:
            workspace_path: Path to git repository root
        """
        self.workspace_path = workspace_path or Path.cwd()

    def detect_generated_artifacts(
        self,
        artifact_paths: Optional[List[str]] = None
    ) -> List[str]:
        """
        Detect which artifact files have been modified.

        Args:
            artifact_paths: Specific artifact paths to check,
                          or None to use KNOWN_ARTIFACTS

        Returns:
            List of modified artifact paths
        """
        paths_to_check = artifact_paths or self.KNOWN_ARTIFACTS

        try:
            result = subprocess.run(
                ['git', 'status', '--porcelain'],
                capture_output=True,
                text=True,
                check=True,
                cwd=self.workspace_path
            )

            modified_files = []
            for line in result.stdout.split('\n'):
                if not line:
                    continue

                # Parse git status output: "XY filename"
                # X = staged status, Y = unstaged status
                status = line[:2]
                # split once on whitespace after status to get the path
                remainder = line[2:].lstrip()
                path = remainder

                # Check for modifications or untracked (M, MM, AM, ??, etc.)
                # Position 0 = staged, Position 1 = unstaged
                if ('M' in status or '?' in status) and path in paths_to_check:
                    modified_files.append(path)

            if modified_files:
                logger.info(
                    f"Detected {len(modified_files)} modified artifacts: "
                    f"{', '.join(modified_files)}"
                )

            return modified_files

        except subprocess.CalledProcessError as e:
            logger.warning(f"Failed to detect generated artifacts: {e}")
            return []
        except Exception:
            logger.error("Unexpected error detecting artifacts")
            return []

    def stash_artifacts(self, artifacts: List[str]) -> Optional[int]:
        """
        Stash specific artifact files before sync operations.

        Args:
            artifacts: List of artifact paths to stash

        Returns:
            Stash index (0 = most recent) if successful, None otherwise
        """
        if not artifacts:
            logger.debug("No artifacts to stash")
            return None

        try:
            timestamp = datetime.now(UTC).strftime('%Y%m%d_%H%M%S')
            stash_message = f"#321 post-commit artifacts {timestamp}"

            # Stage artifacts temporarily (needed for selective stash)
            logger.debug(f"Staging artifacts: {artifacts}")
            subprocess.run(
                ['git', 'add'] + artifacts,
                check=True,
                cwd=self.workspace_path,
                capture_output=True,
                text=True
            )

            # Stash only the staged artifact files
            subprocess.run(
                ['git', 'stash', 'push', '--staged', '-m', stash_message],
                check=True,
                cwd=self.workspace_path,
                capture_output=True,
                text=True
            )

            # Most recent stash is always index 0
            stash_index = 0
            logger.info(
                f"Stashed {len(artifacts)} artifacts "
                f"(index: stash@{{{stash_index}}}): "
                f"{', '.join(artifacts)}"
            )
            return stash_index

        except subprocess.CalledProcessError as e:
            err_msg = f"Failed to stash artifacts: {e}"
            if hasattr(e, 'stdout'):
                err_msg += f"\nstdout: {e.stdout}"
            if hasattr(e, 'stderr'):
                err_msg += f"\nstderr: {e.stderr}"
            logger.error(err_msg)
            return None
        except Exception:
            logger.error("Unexpected error stashing artifacts")
            return None

    def restore_stashed_artifacts(self, stash_index: Optional[int]) -> bool:
        """
        Restore previously stashed artifacts after sync operations.

        Args:
            stash_index: Stash index to restore (0 = most recent)

        Returns:
            True if restore succeeded, False otherwise
        """
        if stash_index is None:
            logger.debug("No stash index provided")
            return True  # No stash to restore is success

        try:
            # Apply and drop the stash using index
            logger.debug(f"Restoring stash@{{{stash_index}}}")
            subprocess.run(
                ['git', 'stash', 'pop', f'stash@{{{stash_index}}}'],
                check=True,
                cwd=self.workspace_path,
                capture_output=True,
                text=True
            )

            logger.info(
                f"Restored artifacts from stash@{{{stash_index}}}"
            )
            return True

        except subprocess.CalledProcessError as e:
            err_msg = (
                f"Failed to restore stashed artifacts: {e}\n"
                f"Stash preserved at stash@{{{stash_index}}} "
                f"for manual recovery"
            )
            if hasattr(e, 'stdout'):
                err_msg += f"\nstdout: {e.stdout}"
            if hasattr(e, 'stderr'):
                err_msg += f"\nstderr: {e.stderr}"
            logger.error(err_msg)
            return False
        except Exception:
            logger.error("Unexpected error restoring artifacts")
            return False

    def handle_sync_artifacts(self, sync_callable):
        """
        Wrapper for sync operations that manages artifacts.

        Pattern:
          1. Detect generated artifacts
          2. Stash artifacts if found
          3. Execute sync operation
          4. Restore artifacts (even if sync fails)

        Args:
            sync_callable: Function to execute sync operation

        Returns:
            Tuple of (sync_result, artifact_info_dict)
        """
        # Phase 1: Detect artifacts
        artifacts = self.detect_generated_artifacts()
        artifact_info = {
            'artifacts_detected': len(artifacts),
            'artifact_paths': artifacts,
            'stash_index': None,
            'restore_success': None
        }

        # Phase 2: Stash if needed
        stash_index = None
        if artifacts:
            stash_index = self.stash_artifacts(artifacts)
            artifact_info['stash_index'] = stash_index

        # Phase 3: Execute sync
        try:
            sync_result = sync_callable()

            # Phase 4: Restore artifacts
            if stash_index is not None:
                restore_success = self.restore_stashed_artifacts(stash_index)
                artifact_info['restore_success'] = restore_success

            return sync_result, artifact_info

        except Exception:
            # Ensure artifacts are restored even on failure
            if stash_index is not None:
                restore_success = self.restore_stashed_artifacts(stash_index)
                artifact_info['restore_success'] = restore_success
            raise
