"""ARC chain import utilities for Aurora CloudBank."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Iterable


ARC_EXPORT_SCHEMA = "ARC_CHAIN_EXPORT_SCHEMA_v1.0"


def _validate_arc_payload(arc_data: Dict[str, Any]) -> Iterable[Dict[str, Any]]:
    """Validate the top-level structure of an ARC export payload.

    Args:
        arc_data: Parsed JSON data from an ARC export file.

    Returns:
        Iterable of ARC chain entries ready for reconstruction.

    Raises:
        ValueError: If any required ARC metadata is missing or invalid.
    """

    schema = arc_data.get("schema")
    if schema != ARC_EXPORT_SCHEMA:
        raise ValueError(
            "Unsupported ARC export schema: "
            f"{schema!r}. Expected {ARC_EXPORT_SCHEMA!r}."
        )

    validation_block = arc_data.get("validation")
    if not isinstance(validation_block, dict) or not validation_block.get(
        "validation_passed"
    ):
        raise ValueError("ARC checksum validation failed.")

    arc_chain = arc_data.get("arc_chain")
    if not isinstance(arc_chain, list):
        raise ValueError("ARC export missing arc_chain entries.")

    return arc_chain


def import_arc_file(arc_file_path: Path | str) -> Dict[str, Dict[str, Any]]:
    """Import an ARC chain export file into a symbolic thread state map.

    Args:
        arc_file_path: Path to a JSON file generated by the ARC export routine.

    Returns:
        A dictionary keyed by ARC entry type with reconstructed metadata.

    Raises:
        FileNotFoundError: If the provided path does not exist.
        ValueError: If the ARC payload fails validation checks.
    """

    path = Path(arc_file_path)
    if not path.is_file():
        raise FileNotFoundError(f"ARC export file not found: {path}")

    with path.open("r", encoding="utf-8") as file_handle:
        arc_data: Dict[str, Any] = json.load(file_handle)

    thread_state: Dict[str, Dict[str, Any]] = {}

    for arc_entry in _validate_arc_payload(arc_data):
        entry_type = arc_entry.get("type")
        if not entry_type:
            raise ValueError("ARC entry missing required type identifier.")

        thread_state[entry_type] = {
            "summary": arc_entry.get("summary"),
            "timestamp": arc_entry.get("timestamp"),
            "by": arc_entry.get("by"),
            "anchor_pair": arc_entry.get("anchor_pair"),
        }

    print(f"[RECALL_ARC] Loaded ARC recap: {len(thread_state)} entries.")
    return thread_state


__all__ = ["import_arc_file", "ARC_EXPORT_SCHEMA"]
