"""Versioned constants for GUMAS Phase-6 sensing/EW/targeting/weapons v1.0."""
from __future__ import annotations

PHASE6_CONTRACT_ID = "GUMAS_SENSING_EW_TARGETING_WEAPONS_v1_0"
PHASE6_VERSION = "1.0.0"
CANONICAL_JSON_PROFILE = "aurora-canonical-json-v1"

CONTACT_MIN_Q1000 = 150
CLASSIFY_SUSPECT_Q1000 = 300
CLASSIFY_HOSTILE_Q1000 = 600
PASSIVE_TRACK_BONUS_Q1000 = 75
PROTECT_NETWORK_MULTIPLIER_Q1000 = 1250
ACTIVE_JAM_TRACK_MULTIPLIER_Q1000 = 500
DECEPTION_TRACK_MULTIPLIER_Q1000 = 150
DECEPTION_IDENTITY_MULTIPLIER_Q1000 = 650

FIRE_CONTACT_THRESHOLD_Q1000 = {
    "HOLD_FIRE": 1001,
    "CONTROLLED_FIRE": 650,
    "MAX_EFFECT_FIRE": 500,
}
TACTICAL_INTENSITY_Q1000 = {
    "HOLD_FIRE": 0,
    "CONTROLLED_FIRE": 650,
    "MAX_EFFECT_FIRE": 1000,
}
LOGISTICS_EXPENDITURE_Q1000 = {
    "CONSERVE": 600,
    "BALANCED_EXPENDITURE": 800,
    "SURGE_EXPENDITURE": 1000,
}
EW_MODES = {
    "PASSIVE_TRACK",
    "PROTECT_NETWORK",
    "ACTIVE_JAM",
    "DECEPTIVE_EMISSIONS",
}
PROTECTED_DISPOSITIONS = {
    "surrendered",
    "disabled",
    "destroyed",
    "noncombatant",
    "protected",
}
