name: Auto Labeler

on:
  push:
    branches:
      - main

jobs:
  label:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Apply labels
        uses: actions/labeler@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/labeler.yml