name: Auto Labeler

on:
  push:
    branches:
      - main

jobs:
  label:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Apply labels
        uses: actions/labeler@9794b1493b6f1fa7b006c5f8635a19c76c98be95  # v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/labeler.yml