name: Codacy Analysis
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  codacy-analysis:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@v3.4.5
        with:
          codacy-repo-token: ${{ secrets.CODACY_REPO_TOKEN }}
