name: Codacy Analysis
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  codacy-analysis:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@562ee3e92b8e92df8b67e0a5ff8aa8e261919c08  # v4.4.7
        with:
          codacy-repo-token: ${{ secrets.CODACY_REPO_TOKEN }}
