name: Code Quality
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code_quality:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Code Quality Checks
        run: echo 'Running code quality checks'