name: Collab Sync
on:
  push:
    branches:
      - main

jobs:
  sync:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sync
        run: echo 'Syncing...'