name: Disable symbolic-bundle workflow  

on:  
  push:  
    branches:  
      - main  
  pull_request:  
    branches:  
      - main  

jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout  
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - name: Run Build  
        run: echo 'Building...'  

      - name: Disable  
        if: false  
        run: echo 'This step will never run'  
